project:
  type: website
  output-dir: docs

website:
  title: "Quantitative Analysis 1"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: syllabus.qmd
        text: Syllabus
      - href: content.qmd
        text: Content
  search: false

format:
  html:
    theme: [cosmo, theme.scss]
    css: styles.css
    toc: true

editor: visual

