---
title: "Thinking Linearly: Things to Remember About Linear Regression"
format: 
  revealjs:
    theme: [default, theme-lecture-slides.scss] 
    css: styles-lecture-slides.css
    slide-number: true
execute:
  echo: true
editor_options: 
  chunk_output_type: console
---

```{r}
#| label: load-packages
#| include: false
source("packages-lecture.R")
source("helper-functions-lecture.R")

```

## Overview 

* Review the final homework assignment
* A retro/review of the course material 

## Things to Remember

1. Linear regression **tries** to answer the question: How does the outcome variable change, on average, when we change the value of a predictor variable. 

2. 4. You do not have to think linearly with a linear model, you can capture nonlinear effects too (interactions & curvilinear effects).

3. Linear regression is a tool and it works wondefully when applied to the right problems (assumptions are generally met), but it can fall apart when applied to the wrong problems. 

4. For all statistical models, do not equate **statistical significance** with **practical significance**--always remember to look at the effect size! 

5. The best policy when using statistics is to **be transparent** about all of the decisions you made to get to your final model. 

## Questions

Speak now or forever hold your peace! 

## Thanks!

Thanks for a great semester! I hope y'all enjoyed the most fascintating, never boring course you could take! 

Feel free to keep in touch!


